apiVersion: v1
kind: Service
metadata:
  name: odoo-service
  labels:
    app: odoo-17
spec:
  type: NodePort
  selector:
    app: odoo-17
    name: odoo-container
  ports:
    - port: 8069
      targetPort: 8069
      nodePort: 30017
  