apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    name: db-deployment
spec:
  selector:
    matchLabels:
      name: db-container
  replicas: 1
  template:
   metadata:
     name: db-container
     labels:
       name: db-container
   spec:
    containers:
     - name: postgres
       image: postgres:15
       ports:
         - containerPort: 5432
       env:
         - name: POSTGRES_PASSWORD
           value: "odoo"
         - name: POSTGRES_USER
           value: "odoo"
         - name: POSTGRES_DB
           value: "postgres" 

    
